server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/hackathon
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: 1234567891234567891234567891234567891234567891234567891234567891234
  expiration: 86400000

twilio:
  account-sid: 
  auth-token:
  whatsapp-from: